FROM mcr.microsoft.com/dotnet/sdk:8.0 AS builder

WORKDIR /src

COPY . .

RUN dotnet restore "BerrySystem.sln"

RUN dotnet publish "BerrySystem.Api/BerrySystem.Api.csproj" -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final

WORKDIR /app

COPY --from=builder /app/publish .

ENTRYPOINT ["dotnet", "BerrySystem.Api.dll"]